### Let's clean bedsheets.csv

### Let me load it first

In [1]:
import pandas as pd

In [2]:
bedSheetsData = pd.read_csv('/Users/negikshitiz/Documents/CelebalTech/Dataset/bedsheets.csv')

### Now that i've loaded it let's explore it.

In [3]:
bedSheetsData.head
bedSheetsData.tail

<bound method NDFrame.tail of     product_id          title  \
0     18602872        My Room
1     18602850        My Room
2      8961147     Story@home
3      8430275      MYTRIDENT
4     18346118         Arrabi
5     18327434     BELLA CASA
6     18492504          ROMEE
7     13729978         DDecor
8     19788630   Home Ecstasy
9     20296382  DREAM WEAVERZ
10    18346134         Arrabi

                                  product_description  rating  ratings_count  \
0   Yellow & Green Floral 140 TC King Bedsheet wit...     4.7             10
1   Ethnic Print 144 TC Super King Bedsheet with 2...     4.5             22
2   Pink & White Floral 160 TC Cotton 1 King Bedsh...     3.7              7
3   Sea Green Floral Flat 120 TC Cotton 1 Queen Be...     4.4             26
4   Pink & White Graphic 300 TC King Bedsheet with...     0.0              0
5                               Unisex Blue Bedsheets     0.0              0
6   Blue & Beige Conversational 160 TC King Bedshe...     3.9             10
7   White & Brown Floral 350 TC Cotton 1 King Beds...     3.6             15
8   140tc Pure Cotton printed Teal Blue Single Bed...     4.5              6
9   Grey & Coral Printed 220 TC Glazed Cotton King...     3.8             18
10  Pink & Grey Striped 300 TC King Cotton Bedshee...     4.3             12

    initial_price  discount  final_price currency  \
0          2999.0      54.0  "₹2,999.00"      INR
1          2999.0      54.0  "₹2,999.00"      INR
2          2199.0      53.0  "₹2,199.00"      INR
3          2199.0      46.0  "₹2,199.00"      INR
4          3329.0      74.0    "₹865.00"      INR
5          1499.0      73.0    "₹404.00"      INR
6          3499.0      65.0  "₹3,499.00"      INR
7          1599.0      20.0  "₹1,599.00"      INR
8          1199.0      42.0  "₹1,199.00"      INR
9          2599.0      78.0  "₹2,599.00"      INR
10         6329.0      76.0  "₹6,329.00"      INR

                                               images  ...  \
0   http://assets.myntassets.com/assets/images/186...  ...
1   http://assets.myntassets.com/assets/images/186...  ...
2   http://assets.myntassets.com/assets/images/896...  ...
3   http://assets.myntassets.com/assets/images/pro...  ...
4   http://assets.myntassets.com/assets/images/183...  ...
5   http://assets.myntassets.com/assets/images/183...  ...
6   http://assets.myntassets.com/assets/images/184...  ...
7   http://assets.myntassets.com/assets/images/137...  ...
8   http://assets.myntassets.com/assets/images/197...  ...
9   http://assets.myntassets.com/assets/images/202...  ...
10  http://assets.myntassets.com/assets/images/183...  ...

                                      amount_of_stars what_customers_said  \
0   {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...                 NaN
1   {"1_star":1,"2_stars":1,"3_stars":1,"4_stars":...                 NaN
2   {"1_star":1,"2_stars":1,"3_stars":0,"4_stars":...                 NaN
3   {"1_star":0,"2_stars":1,"3_stars":2,"4_stars":...                 NaN
4   {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...                 NaN
5   {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...                 NaN
6   {"1_star":1,"2_stars":1,"3_stars":1,"4_stars":...                 NaN
7   {"1_star":4,"2_stars":1,"3_stars":0,"4_stars":...                 NaN
8   {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...                 NaN
9   {"1_star":2,"2_stars":1,"3_stars":3,"4_stars":...                 NaN
10  {"1_star":1,"2_stars":0,"3_stars":1,"4_stars":...                 NaN

                             seller_name  \
0                                    NaN
1                                    NaN
2                                    NaN
3                                    NaN
4                         Sig███Ove███as
5   Bel███Cas███ash█████████ail█████████
6                                    NaN
7                                    NaN
8                                    NaN
9                                    NaN
10                                   NaN

                                                sizes videos  \
0   [{"size":"Single"},{"size":"Double Queen"},{"s...    NaN
1                             [{"size":"Super King"}]    NaN
2                            [{"size":"Double King"}]    NaN
3                           [{"size":"Double Queen"}]    NaN
4                             [{"size":"Super King"}]    NaN
5                                 [{"size":"Single"}]    NaN
6                            [{"size":"Double King"}]    NaN
7                            [{"size":"Double King"}]    NaN
8         [{"size":"Single"},{"size":"Double Queen"}]    NaN
9                           [{"size":"Double Queen"}]    NaN
10                            [{"size":"Super King"}]    NaN

                                   seller_information  \
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4   Old███. 2███162█████████o. ███████████████████...
5   E-1███103███PIP█████████ IN███████████████████...
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN

                                     variations  \
0                                          [{}]
1                                          [{}]
2                                       [{},{}]
3                        [{},{},{},{},{},{},{}]
4                              [{},{},{},{},{}]
5   [{},{},{},{},{},{},{},{},{},{},{},{},{},{}]
6                                          [{}]
7                                          [{}]
8                                       [{},{}]
9                                 [{},{},{},{}]
10                          [{},{},{},{},{},{}]

                                           best_offer  \
0                                                  {}
1                                                  {}
2                                                  {}
3                                                  {}
4   {"applicable_on":"Orders above Rs. 999 (only o...
5   {"applicable_on":"Orders above Rs. 649 (only o...
6                                                  {}
7                                                  {}
8                                                  {}
9                                                  {}
10                                                 {}

                                          more_offers   category
0   [{"offer_name":"10% Instant Discount on Citi C...  bedsheets
1   [{"offer_name":"10% Instant Discount on Citi C...  bedsheets
2   [{"offer_name":"10% Instant Discount on Citi C...  bedsheets
3   [{"offer_name":"10% Instant Discount on Citi C...  bedsheets
4   [{"offer_name":"10% Instant Discount on IndusI...  bedsheets
5   [{"offer_name":"10% Instant Discount on IndusI...  bedsheets
6   [{"offer_name":"10% Instant Discount on Citi C...  bedsheets
7   [{"offer_name":"10% Instant Discount on Citi C...  bedsheets
8   [{"offer_name":"10% Instant Discount on Citi C...  bedsheets
9   [{"offer_name":"10% Instant Discount on Citi C...  bedsheets
10  [{"offer_name":"10% Instant Discount on Citi C...  bedsheets

[11 rows x 24 columns]>

### Shape of dataset

In [4]:
print(bedSheetsData.shape)

(11, 24)

### What about column name?

In [5]:
print(bedSheetsData.columns)

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='str')

### What about their dataTypes

In [6]:
print(bedSheetsData.dtypes)

product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price             float64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said       float64
seller_name                   str
sizes                         str
videos                    float64
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

### Let's see missing values

In [7]:
missingWhere = bedSheetsData.isnull()
print(missingWhere)

    product_id  title  product_description  rating  ratings_count  \
0        False  False                False   False          False
1        False  False                False   False          False
2        False  False                False   False          False
3        False  False                False   False          False
4        False  False                False   False          False
5        False  False                False   False          False
6        False  False                False   False          False
7        False  False                False   False          False
8        False  False                False   False          False
9        False  False                False   False          False
10       False  False                False   False          False

    initial_price  discount  final_price  currency  images  ...  \
0           False     False        False     False   False  ...
1           False     False        False     False   False  ...
2           False     False        False     False   False  ...
3           False     False        False     False   False  ...
4           False     False        False     False   False  ...
5           False     False        False     False   False  ...
6           False     False        False     False   False  ...
7           False     False        False     False   False  ...
8           False     False        False     False   False  ...
9           False     False        False     False   False  ...
10          False     False        False     False   False  ...

    amount_of_stars  what_customers_said  seller_name  sizes  videos  \
0             False                 True         True  False    True
1             False                 True         True  False    True
2             False                 True         True  False    True
3             False                 True         True  False    True
4             False                 True        False  False    True
5             False                 True        False  False    True
6             False                 True         True  False    True
7             False                 True         True  False    True
8             False                 True         True  False    True
9             False                 True         True  False    True
10            False                 True         True  False    True

    seller_information  variations  best_offer  more_offers  category
0                 True       False       False        False     False
1                 True       False       False        False     False
2                 True       False       False        False     False
3                 True       False       False        False     False
4                False       False       False        False     False
5                False       False       False        False     False
6                 True       False       False        False     False
7                 True       False       False        False     False
8                 True       False       False        False     False
9                 True       False       False        False     False
10                True       False       False        False     False

[11 rows x 24 columns]

### Let's see count of null values per column

In [8]:
bedSheetsData.isnull().sum()

product_id                 0
title                      0
product_description        0
rating                     0
ratings_count              0
initial_price              0
discount                   0
final_price                0
currency                   0
images                     0
delivery_options           0
product_details            0
breadcrumbs                0
product_specifications     0
amount_of_stars            0
what_customers_said       11
seller_name                9
sizes                      0
videos                    11
seller_information         9
variations                 0
best_offer                 0
more_offers                0
category                   0
dtype: int64

### Let's see if their are duplicate values

In [9]:
bedSheetsData.drop_duplicates(subset=["product_id"], inplace=True)

### We can see that 'what_customers_said', 'videos', and 'seller_information' have mostly null values so lets drop em

In [10]:
bedSheetsData = bedSheetsData.drop({'what_customers_said', 'seller_information', 'videos'}, axis=1)

In [11]:
print(bedSheetsData.to_string())

    product_id          title                                                           product_description  rating  ratings_count  initial_price  discount  final_price currency                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         images                                                                                      delivery_options                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    product_details                                                                                                                                                                                                                                                                                 breadcrumbs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     product_specifications                                                amount_of_stars                           seller_name                                                              sizes                                   variations                                                                                                                                                                        best_offer                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      more_offers   category
0     18602872        My Room               Yellow & Green Floral 140 TC King Bedsheet with 2 Pillow Covers     4.7             10         2999.0      54.0  "₹2,999.00"      INR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    http://assets.myntassets.com/assets/images/18602872/2022/8/16/fd780651-1615-47e7-bb13-216afd52f25f1660639355241-My-Room-Yellow--Green-Floral-140-TC-King-Bedsheet-with-2-Pil-1.jpg,http://assets.myntassets.com/assets/images/18602872/2022/8/16/e845a5a5-bccf-4ef2-b796-221a2af13d961660639355231-My-Room-Yellow--Green-Floral-140-TC-King-Bedsheet-with-2-Pil-2.jpg,http://assets.myntassets.com/assets/images/18602872/2022/8/16/a149b1bb-9b67-412f-88b3-89827d4141201660639355220-My-Room-Yellow--Green-Floral-140-TC-King-Bedsheet-with-2-Pil-3.jpg,http://assets.myntassets.com/assets/images/18602872/2022/8/16/9d555f58-8501-4d58-abeb-57ac6f3101c01660639355209-My-Room-Yellow--Green-Floral-140-TC-King-Bedsheet-with-2-Pil-4.jpg  ["100% Original Products","Pay on delivery might be available","Easy 14 days returns and exchanges"]                                                                                                                                                                                                                                                                                                                                                                                                                                 {"description":"Set content: 1 king bedsheet with 2 pillow covers  Quality: fine  Thread count: 140  Colour: yellow and green  Pattern: floral","material_and_care":"Cotton. Machine wash cold. Wash dark colours seperately. Do not soak. Do not bleach, tumble dry low , warm iron if necessary","size_and_fit":"1N King bedsheet 2.74 metre x 2.74 metre &amp; 2N Pillow Covers 43cms x 68cms"}                          [{"name":"Unisex","url":"https://www.myntra.com/unisex-home"},{"name":"Bedsheets","url":"https://www.myntra.com/bedsheets"},{"name":"My Room","url":"https://www.myntra.com/my-room-bedsheets"},{"name":"More by My Room","url":"https://www.myntra.com/my-room"}]                                                                                            [{"specification_name":"Bed Size","specification_value":"King"},{"specification_name":"Fabric","specification_value":"Cotton"},{"specification_name":"GSM","specification_value":"NA"},{"specification_name":"Number of Bedsheets","specification_value":"1"},{"specification_name":"Number of Pillow Covers","specification_value":"2"},{"specification_name":"Print or Pattern Type","specification_value":"Floral"},{"specification_name":"Quality","specification_value":"Fine"},{"specification_name":"Sustainable","specification_value":"Regular"},{"specification_name":"Thread Count","specification_value":"140"},{"specification_name":"Type","specification_value":"Flat"},{"specification_name":"Wash Care","specification_value":"Machine Wash"}]   {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":3,"5_stars":7}                                   NaN  [{"size":"Single"},{"size":"Double Queen"},{"size":"Super King"}]                                         [{}]                                                                                                                                                                                {}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             [{"offer_name":"10% Instant Discount on Citi Credit & Debit Cards ","offer_value":" Min Spend ₹3,000; Max Discount ₹1,000. "},{"offer_name":"EMI option available"}]  bedsheets
1     18602850        My Room                  Ethnic Print 144 TC Super King Bedsheet with 2 Pillow Covers     4.5             22         2999.0      54.0  "₹2,999.00"      INR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            http://assets.myntassets.com/assets/images/18602850/2022/8/16/990a6062-8048-47e4-adb2-92709b8a6d531660639260775-My-Room-Unisex-Grey-Bedsheets-1011660639260505-1.jpg,http://assets.myntassets.com/assets/images/18602850/2022/8/16/d4245a24-5d74-42c0-a3a4-b9605bf3abca1660639260766-My-Room-Unisex-Grey-Bedsheets-1011660639260505-2.jpg,http://assets.myntassets.com/assets/images/18602850/2022/8/16/b7899064-7d84-4398-9d59-44cfe8f3c3651660639260755-My-Room-Unisex-Grey-Bedsheets-1011660639260505-3.jpg,http://assets.myntassets.com/assets/images/18602850/2022/8/16/78cdc6b9-1c6a-473e-94a5-a50782f15cb31660639260745-My-Room-Unisex-Grey-Bedsheets-1011660639260505-4.jpg  ["100% Original Products","Pay on delivery might be available","Easy 14 days returns and exchanges"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           {"description":"Dimensions: Super King bedsheet 2.74 metre x 2.74 metre & 2N Pillow Covers 43cms x 68cms","material_and_care":"Machine wash cold. Wash dark colours seperately. Do not soak. Do not bleach, tumble dry low , warm iron if necessary","size_and_fit":"/"}                          [{"name":"Unisex","url":"https://www.myntra.com/unisex-home"},{"name":"Bedsheets","url":"https://www.myntra.com/bedsheets"},{"name":"My Room","url":"https://www.myntra.com/my-room-bedsheets"},{"name":"More by My Room","url":"https://www.myntra.com/my-room"}]                                                                                       [{"specification_name":"Bed Size","specification_value":"King"},{"specification_name":"Fabric","specification_value":"Cotton"},{"specification_name":"GSM","specification_value":"NA"},{"specification_name":"Number of Bedsheets","specification_value":"1"},{"specification_name":"Number of Pillow Covers","specification_value":"2"},{"specification_name":"Print or Pattern Type","specification_value":"Abstract"},{"specification_name":"Quality","specification_value":"Regular"},{"specification_name":"Sustainable","specification_value":"Regular"},{"specification_name":"Thread Count","specification_value":"140"},{"specification_name":"Type","specification_value":"Flat"},{"specification_name":"Wash Care","specification_value":"Machine Wash"}]  {"1_star":1,"2_stars":1,"3_stars":1,"4_stars":2,"5_stars":17}                                   NaN                                            [{"size":"Super King"}]                                         [{}]                                                                                                                                                                                {}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             [{"offer_name":"10% Instant Discount on Citi Credit & Debit Cards ","offer_value":" Min Spend ₹3,000; Max Discount ₹1,000. "},{"offer_name":"EMI option available"}]  bedsheets
2      8961147     Story@home        Pink & White Floral 160 TC Cotton 1 King Bedsheet with 2 Pillow Covers     3.7              7         2199.0      53.0  "₹2,199.00"      INR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    http://assets.myntassets.com/assets/images/8961147/2021/7/5/26d0354d-96cb-49a3-bc8e-45cb9059d8fe1625469256587StoryhomePinkWhiteFloral160TCCotton1KingBedsheetwith2PillowC1.jpg,http://assets.myntassets.com/assets/images/8961147/2021/7/5/3b477da3-76e6-43f0-ad3e-096f5c89fdca1625469256597StoryhomePinkWhiteFloral160TCCotton1KingBedsheetwith2PillowC2.jpg,http://assets.myntassets.com/assets/images/8961147/2021/7/5/5cff65bc-ec5f-4533-a75a-63894c0f9e6c1625469256606StoryhomePinkWhiteFloral160TCCotton1KingBedsheetwith2PillowC3.jpg,http://assets.myntassets.com/assets/images/8961147/2021/7/5/6c380918-d78e-479b-aad4-d0c6041799561625469256617StoryhomePinkWhiteFloral160TCCotton1KingBedsheetwith2PillowC4.jpg  ["100% Original Products","Pay on delivery might be available","Easy 14 days returns and exchanges"]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             {"description":"Set content: 1 King bedsheet with 2 pillow coversQuality: RegularThread count: 160Colour: Pink and WhitePattern: Floral","material_and_care":"100% Cotton. Machine-wash","size_and_fit":"King bedsheet: 2.7 metres&nbsp;x 2.7 metres (length x width). Pillow covers: 69 cm x 46 cm (length x width)"}              [{"name":"Unisex","url":"https://www.myntra.com/unisex-home"},{"name":"Bedsheets","url":"https://www.myntra.com/bedsheets"},{"name":"Story@home","url":"https://www.myntra.com/story@home-bedsheets"},{"name":"More by Story@home","url":"https://www.myntra.com/story@home"}]                                                                                                                                                                                                                      [{"specification_name":"Bed Size","specification_value":"King"},{"specification_name":"Fabric","specification_value":"Cotton"},{"specification_name":"Number of Bedsheets","specification_value":"1"},{"specification_name":"Number of Pillow Covers","specification_value":"2"},{"specification_name":"Print or Pattern Type","specification_value":"Floral"},{"specification_name":"Quality","specification_value":"Regular"},{"specification_name":"Thread Count","specification_value":"160"},{"specification_name":"Type","specification_value":"Flat"},{"specification_name":"Wash Care","specification_value":"Machine Wash"}]   {"1_star":1,"2_stars":1,"3_stars":0,"4_stars":2,"5_stars":3}                                   NaN                                           [{"size":"Double King"}]                                      [{},{}]                                                                                                                                                                                {}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             [{"offer_name":"10% Instant Discount on Citi Credit & Debit Cards ","offer_value":" Min Spend ₹3,000; Max Discount ₹1,000. "},{"offer_name":"EMI option available"}]  bedsheets

### oh i forgot to drop sellerName it's mostly null

In [12]:
bedSheetsData.drop('seller_name', axis=1)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,delivery_options,product_details,breadcrumbs,product_specifications,amount_of_stars,sizes,variations,best_offer,more_offers,category
0,18602872,My Room,Yellow & Green Floral 140 TC King Bedsheet wit...,4.7,10,2999.0,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Set content: 1 king bedsheet w...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Bed Size"",""specificati...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""size"":""Single""},{""size"":""Double Queen""},{""s...",[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
1,18602850,My Room,Ethnic Print 144 TC Super King Bedsheet with 2...,4.5,22,2999.0,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Dimensions: Super King bedshee...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Bed Size"",""specificati...","{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...","[{""size"":""Super King""}]",[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
2,8961147,Story@home,Pink & White Floral 160 TC Cotton 1 King Bedsh...,3.7,7,2199.0,53.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/896...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Set content: 1 King bedsheet w...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Bed Size"",""specificati...","{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...","[{""size"":""Double King""}]","[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
3,8430275,MYTRIDENT,Sea Green Floral Flat 120 TC Cotton 1 Queen Be...,4.4,26,2199.0,46.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/pro...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Set content: 1 Queen bedsheet ...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Bed Size"",""specificati...","{""1_star"":0,""2_stars"":1,""3_stars"":2,""4_stars"":...","[{""size"":""Double Queen""}]","[{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
4,18346118,Arrabi,Pink & White Graphic 300 TC King Bedsheet with...,0.0,0,3329.0,74.0,"""₹865.00""",INR,http://assets.myntassets.com/assets/images/183...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Set Content: 1 King Bedsheet w...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Bed Size"",""specificati...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""size"":""Super King""}]","[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bedsheets
5,18327434,BELLA CASA,Unisex Blue Bedsheets,0.0,0,1499.0,73.0,"""₹404.00""",INR,http://assets.myntassets.com/assets/images/183...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""WHAT YOU GET : 1 Double Bedshe...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Bed Size"",""specificati...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""size"":""Single""}]","[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bedsheets
6,18492504,ROMEE,Blue & Beige Conversational 160 TC King Bedshe...,3.9,10,3499.0,65.0,"""₹3,499.00""",INR,http://assets.myntassets.com/assets/images/184...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Set content: 1 king bedsheet w...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Bed Size"",""specificati...","{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...","[{""size"":""Double King""}]",[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
7,13729978,DDecor,White & Brown Floral 350 TC Cotton 1 King Beds...,3.6,15,1599.0,20.0,"""₹1,599.00""",INR,http://assets.myntassets.com/assets/images/137...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Set content: 1 King bedsheet w...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Bed Size"",""specificati...","{""1_star"":4,""2_stars"":1,""3_stars"":0,""4_stars"":...","[{""size"":""Double King""}]",[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
8,19788630,Home Ecstasy,140tc Pure Cotton printed Teal Blue Single Bed...,4.5,6,1199.0,42.0,"""₹1,199.00""",INR,http://assets.myntassets.com/assets/images/197...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""140tc 100% Cotton Printed Teal...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Bed Size"",""specificati...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""size"":""Single""},{""size"":""Double Queen""}]","[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
9,20296382,DREAM WEAVERZ,Grey & Coral Printed 220 TC Glazed Cotton King...,3.8,18,2599.0,78.0,"""₹2,599.00""",INR,http://assets.myntassets.com/assets/images/202...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Set Content : 1 King bedsheet ...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Bed Size"",""specificati...","{""1_star"":2,""2_stars"":1,""3_stars"":3,""4_stars"":...","[{""size"":""Double Queen""}]","[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
10,18346134,Arrabi,Pink & Grey Striped 300 TC King Cotton Bedshee...,4.3,12,6329.0,76.0,"""₹6,329.00""",INR,http://assets.myntassets.com/assets/images/183...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Set content: 1 king bedsheet w...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Bed Size"",""specificati...","{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""size"":""Super King""}]","[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets

### Let's go with the some operations that i can perform on the dataset

In [14]:
highRating = bedSheetsData[bedSheetsData["rating"] >= 3.5]
highRating.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,product_details,breadcrumbs,product_specifications,amount_of_stars,seller_name,sizes,variations,best_offer,more_offers,category
0,18602872,My Room,Yellow & Green Floral 140 TC King Bedsheet wit...,4.7,10,2999.0,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""description"":""Set content: 1 king bedsheet w...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Bed Size"",""specificati...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,"[{""size"":""Single""},{""size"":""Double Queen""},{""s...",[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
1,18602850,My Room,Ethnic Print 144 TC Super King Bedsheet with 2...,4.5,22,2999.0,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""description"":""Dimensions: Super King bedshee...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Bed Size"",""specificati...","{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,"[{""size"":""Super King""}]",[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
2,8961147,Story@home,Pink & White Floral 160 TC Cotton 1 King Bedsh...,3.7,7,2199.0,53.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/896...,...,"{""description"":""Set content: 1 King bedsheet w...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Bed Size"",""specificati...","{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,"[{""size"":""Double King""}]","[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
3,8430275,MYTRIDENT,Sea Green Floral Flat 120 TC Cotton 1 Queen Be...,4.4,26,2199.0,46.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""description"":""Set content: 1 Queen bedsheet ...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Bed Size"",""specificati...","{""1_star"":0,""2_stars"":1,""3_stars"":2,""4_stars"":...",NaN,"[{""size"":""Double Queen""}]","[{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
6,18492504,ROMEE,Blue & Beige Conversational 160 TC King Bedshe...,3.9,10,3499.0,65.0,"""₹3,499.00""",INR,http://assets.myntassets.com/assets/images/184...,...,"{""description"":""Set content: 1 king bedsheet w...","[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Bed Size"",""specificati...","{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,"[{""size"":""Double King""}]",[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets

In [15]:
result = bedSheetsData.loc[
    bedSheetsData["rating"] >= 4.0,
    ["title", "rating", "final_price"]
]
print(result.head())

           title  rating  final_price
0        My Room     4.7  "₹2,999.00"
1        My Room     4.5  "₹2,999.00"
3      MYTRIDENT     4.4  "₹2,199.00"
8   Home Ecstasy     4.5  "₹1,199.00"
10        Arrabi     4.3  "₹6,329.00"